# Generated by Django 4.1.5 on 2023-01-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration', models.PositiveSmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('credit', models.PositiveSmallIntegerField()),
                ('teacher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('dateOfBirth', models.DateField()),
                ('sex', models.CharField(choices=[('F', 'feminine'), ('M', 'masculine')], default='M', max_length=1)),
                ('validity', models.BooleanField(default=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.career')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollmentDate', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academy.student')),
            ],
        ),
    ]
